language: node_js
node_js:
  - "node"

before_install:
  - npm i yarn -g
  - yarn config set registry https://registry.npm.taobao.org
  - yarn config set sass-binary-site http://npm.taobao.org/mirrors/node-sass
script: yarn build

after_script:
  - cd ./public
  - git init
  - git config --global user.name "taoeer"  #修改name
  - git config --global user.email "719012229@qq.com"  #修改email
  - git add .
  - git commit -m "update"
  - git push -f --set-upstream https://${GITHUB_TOKEN}@${GH_REF} master

  env:
    global:
      - GH_REF: github.com/taoeer/taoeer.github.io.git
cache:
  directories:
  - node_modules