language: node_js
node_js:
  - "node"

before_install:
  - yarn config set registry https://registry.npm.taobao.org
  - yarn config set sass-binary-site http://npm.taobao.org/mirrors/node-sass
script: yarn build

deploy:
  repo: taoeer.github.io
  local_dir: public
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master